packages:
  - modules/*
  - plugin
  - sites/*
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.22.0+sha512-fdLb4xOZfJcyD01rrgm4RT5UR5quezgLY0chciH1oMVq0ogDiAHxlEqJOltS08Rq6WuzBJoV74yysA9T7DkSuA==
loglevel: info
minimumReleaseAgeExclude:
  - "@types/hast@3.0.5"
  - prettier@3.9.5
